variables:
    - name: SYMFONY_ENV
      value: prod
    - name: YVES_HOST
      value: ${SERVICE_YVES_PUBLIC_ENDPOINT}
    - name: ZED_HOST
      value: ${SERVICE_ZED_PUBLIC_ENDPOINT}

tasks:
    images:
        build:
            services:
                yves:
                    image: ${IMAGE_NAME}
                    naming_strategy: sha1
                zed:
                    image: ${IMAGE_NAME}
                    naming_strategy: sha1
    deployment:
        deploy:
            cluster: ${CLUSTER}
            environment:
                name: '"spryker-" ~ code_reference.branch'
            services:
                yves:
                    specification:
                        accessibility:
                            from_external: true
                        environment_variables:
                            - name: SYMFONY_ENV
                              value: ${SYMFONY_ENV}
                            - name: APPLICATION_ENV
                              value: development-docker
                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 80
                zed:
                    specification:
                        accessibility:
                            from_external: true
                        environment_variables:
                            - name: SYMFONY_ENV
                              value: ${SYMFONY_ENV}
                            - name: APPLICATION_ENV
                              value: development-docker
                            - name: ZED_HOST
                              value: ${ZED_HOST}
                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 80
                redis:
                    specification:
                        volumes:
                            - type: persistent
                              name: redis-volume
                              capacity: 5Gi
                              storage_class: default
                        volume_mounts:
                            - name: redis-volume
                              mount_path: /data
                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 6379
                elasticsearch:
                    specification:
                        volumes:
                            - type: persistent
                              name: elasticsearch-volume
                              capacity: 5Gi
                              storage_class: default
                        volume_mounts:
                            - name: elasticsearch-volume
                              mount_path: /usr/share/elasticsearch/data
                        ports:
                            - identifier: es
                              port: 9200
                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 9200
                postgres:
                    specification:
                        volumes:
                            - type: persistent
                              name: database-volume
                              capacity: 5Gi
                              storage_class: default
                        volume_mounts:
                            - name: database-volume
                              mount_path: /var/lib/postgresql/data
                        environment_variables:
                            - name: PGDATA
                              value: /var/lib/postgresql/data/pgdata
                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 5432
    initialization:
        run:
            cluster: ${CLUSTER}
            image:
                from_service: zed

            environment:
                name: '"spryker-" ~ code_reference.branch'

            commands:
                - vendor/bin/console setup:install
                - vendor/bin/console import:demo-data
                - vendor/bin/console collector:search:export
                - vendor/bin/console collector:storage:export
                - vendor/bin/console setup:search
                - vendor/bin/console application:build-navigation-cache

            environment_variables:
                - name: SYMFONY_ENV
                  value: ${SYMFONY_ENV}
                - name: APPLICATION_ENV
                  value: development-docker

        filter:
            expression: 'tasks.deployment.services.postgres.created'


pipelines:
    - name: Production
      condition: 'not(code_reference.branch matches "/^cpdev/")'
      tasks: [ images, deployment, initialization ]
      variables:
          - name: APPLICATION_ENV
            value: development-docker
    - name: Remote
      condition: 'code_reference.branch matches "/^cpdev/"'
      tasks: [ images, deployment, initialization ]
      variables:
          - name: SYMFONY_ENV
            value: dev

