version: "2"
services:
    web:
        build: .
        expose:
            - 80
            - 443
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/app
        depends_on:
            - redis
            - elasticsearch
            - postgres
        environment:
            - WEB_DIRECTORY=/app/public/Yves
            - APPLICATION_ENV=development-docker
            - WEB_REVERSE_PROXIED="true"
            - WEB_HTTPS="false"
            - YVES_HOST="localhost"
    redis:
        image: redis:3.0
    elasticsearch:
        image: elasticsearch:5.1
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=spryker_user
            - POSTGRES_PASSWORD=spryker_password
            - POSTGRES_DB=spryker
